# This workflow will install Python dependencies, run tests, run linting, and build docs
name: Building Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/w5r9l1c8/dev-swsoc-docker-lambda-base:latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Build docs
      run: sphinx-build docs docs/_build/html -W -b html